### ISSUE TITLE
Add Github lable: Torchsharp

### ISSUE THREAD

**Issue by GeorgeS2019** [ds5678/TorchCategorizationDemo#1]
![image](https://github.com/ds5678/TorchCategorizationDemo/assets/49812372/6323b634-2247-4be6-9ebf-66c0d927590d)

**Comment by ds5678** [comment]
I added it.

How did you find my repository?

**Comment by GeorgeS2019** [comment]
I search github and collect as many people who recently has started trying TorchSharp  :-)

==> Keep trying TorchSharp !
